export const enum StatusCode {
  SUCCESS = 1,
  ERROR = 2,
  CANCEL = 3,
}

export enum Channels {
  SELECT_FILE = 'SELECT_FILE',
  SAVE_FILE = 'SAVE_FILE',
  COMPRESS_FILE = 'COMPRESS_FILE',
  CROP_FILE = 'CROP_FILE',
  SELECT_DIRECTORY = 'SELECT_DIRECTORY',
  DOWNLOAD_FILE = 'DOWNLOAD_FILe',
}