export const enum StatusCode {
  SUCCESS = 1,
  ERROR = 2,
  CANCEL = 3,
}

export enum Channels {
  SELECT_IMAGE = 'SELECT_IMAGE',
  SAVE_IMAGE = 'SAVEIMAGEE',
  COMPRESS_IMAGE = 'COMPRESS_IMAGE',
  CROP_IMAGE = 'CROP_IMAGE',
  SELECT_DIRECTORY = 'SELECT_DIRECTORY',
  DOWNLOAD_IMAGE = 'DOWNLOAD_IMAGE',
  SELECT_SAVE_PATH = 'SELECT_SAVE_PATH',
  GET_SAVE_PATH = 'GET_SAVE_PATH',
  SET_SAVE_PATH = 'SET_SAVE_PATH',
  REMOVE_SAVE_PATH = 'REMOVE_SAVE_PATH',
  SETTINGS = 'SETTINGS',
}